[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bfi_staking = "3gbCKLUwbRTeGKP12jvPFDP8H3jWPVgAeitrMG92k4KH"

[programs.mainnet]
bfi_staking = "3gbCKLUwbRTeGKP12jvPFDP8H3jWPVgAeitrMG92k4KH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/jmf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
