[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bfi_staking = "BgaUuJPsfJEfJo3XYmrJGMxqSvVVwu6MmwQob8c3QgvW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jmf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
